services:
  - type: web
    name: resumeiq-api
    runtime: python
    region: oregon
    plan: starter

    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"

      - key: TOKENIZERS_PARALLELISM
        value: "false"

      - key: SENTENCE_TRANSFORMERS_HOME
        value: /tmp/sbert_cache
